---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-node.fullname" . }}
  labels:
    app: {{ template "besu-node.fullname" . }}
    chart: {{ template "besu-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ template "besu-node.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.besu.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.besu.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.besu.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: rlpx
      protocol: TCP   
{{- if or ( eq .Values.deploy.typenode "writer" ) ( eq .Values.deploy.typenode "tessera" ) }}
    - name: nginx
      port: 80
      targetPort: nginx
      protocol: TCP
{{- end }} 
{{- if .Values.quorumFlags.privacy }}          
    - name: tessera
      port: {{ .Values.node.tessera.port }}
      targetPort: tessera
      protocol: TCP
    - name: tessera-tp
      port: {{ .Values.node.tessera.tpport }}
      targetPort: tessera-besu
      protocol: TCP
{{- end }}
  loadBalancerIP: {{ .Values.deploy.publicIP }}