---

- name: Print some info information 
  vars: 
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible Dist version: {{ ansible_distribution_major_version }}
        
  debug: 
    msg: "{{ msg.split('\n') }}"
  
- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "ubuntu-dependencies.yml"
  when: ansible_distribution |lower == 'ubuntu'


- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "rhel-dependencies.yml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos' and ansible_distribution_major_version < "8") 

- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "centos8-dependencies.yml"
  when: (ansible_distribution |lower == 'centos' and ansible_distribution_major_version == "8") 


- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-centos.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos' and ansible_distribution_major_version < "8")  

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-centos8.yaml"
  when: (ansible_distribution |lower == 'centos' and ansible_distribution_major_version == "8")  

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-redhat.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')


- name: install Besu
  import_tasks: "install-besu.yaml"

- name: init besu
  import_tasks: "init-besu.yaml"

- name: install nginx
  import_tasks: "prepare-nginx.yml"

- name: init tunning
  import_tasks: "init-tuning.yaml"

- name: start node
  import_tasks: "start-node.yaml"

- name: install relay signer
  import_tasks: "install-relay-signer.yaml"
  when: (networkT == '0') or (networkT == '1') # relay-signer is disable on pro-testnet

- name: start ethstats client             
  import_tasks: "start-ethstats-client.yaml"


